// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzfhoQwgXJA9fXvVDZRS6VSc0sUBuhzBM',
    appId: '1:850293297578:web:cf7e06ea98cd178fdd1bd3',
    messagingSenderId: '850293297578',
    projectId: 'fir-test-115',
    authDomain: 'fir-test-115.firebaseapp.com',
    storageBucket: 'fir-test-115.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6rks7Gzp2FnjuCQBpZmtpZibYF9fqQC8',
    appId: '1:850293297578:android:9af43022632610c1dd1bd3',
    messagingSenderId: '850293297578',
    projectId: 'fir-test-115',
    storageBucket: 'fir-test-115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyNr1O1zCQltcy71hK9FuEN7cgOz_vnE8',
    appId: '1:850293297578:ios:72deab9f1bae9d52dd1bd3',
    messagingSenderId: '850293297578',
    projectId: 'fir-test-115',
    storageBucket: 'fir-test-115.appspot.com',
    iosClientId: '850293297578-ti24g7tv0qpj8tso61uqoulrch8m01tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest115',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyNr1O1zCQltcy71hK9FuEN7cgOz_vnE8',
    appId: '1:850293297578:ios:72deab9f1bae9d52dd1bd3',
    messagingSenderId: '850293297578',
    projectId: 'fir-test-115',
    storageBucket: 'fir-test-115.appspot.com',
    iosClientId: '850293297578-ti24g7tv0qpj8tso61uqoulrch8m01tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest115',
  );
}
